Allow selectors and replacements to be registered late
minkphp/Mink pull request #789
Opened 2019-10-11 04:59 UTC by andrewnicols

This allows projects using Mink to create their Named and Partial
selectors, and then to add additional replacements and selectors to be
registered for subsequent use.

This is particularly useful in projects with a distributed plugin
architecture which also which to make use of replacements and selectors
without abusing Reflection to do so.

This is something that we currently do in Moodle for Behat for exactly this reason:
Our hack with Reflection to access the properties to allow proper translation: https://github.com/andrewnicols/moodle/blob/MDL-66559-master/lib/behat/classes/named_selector.php#L48
Registration of plugin replacements and selectors: https://github.com/andrewnicols/moodle/blob/MDL-66559-master/lib/tests/behat/behat_hooks.php#L743

2021-06-01 00:34 UTC, andrewnicols commented
Is there anything that we can do to see this land?

It's extremely helpful and powerful to be able to add additional locators and replacements to the various Selector classes, and being able to make use of Mink replacements in our own named selectors in this way is a huge benefit.

2021-06-02 12:26 UTC, aik099 commented on tests/Selector/NamedSelectorTest.php
> +        return array(
With all these replacements in place, I'm not clearly seeing from the test code what each fixture should find (what the final selector for search should look like). 

Please add some comments about each fixture with selectors .

2021-06-02 12:27 UTC, aik099 requested changes

2021-06-02 12:27 UTC, aik099 commented on tests/Selector/NamedSelectorTest.php
> +            'lateSelectorUsingLateReplacement' => array(
With all these replacements in place, I'm not clearly seeing from the test code what each fixture should find (what the final selector for search should look like). 

Please add some comments about each fixture with the CSS selectors, that are supposed to be found.

2021-06-03 03:02 UTC, andrewnicols commented
I've updated the unit test to more clearly document the provided data an expectations.

I hope that this clarifies things. Please let me know if you can think of a better solution to this.

Thanks

2021-06-03 04:06 UTC, andrewnicols commented
Note: Travis tests are failing because xdebug is not enabled by default for the coverage reports.

2021-06-04 18:50 UTC, aik099 approved these changes

2021-06-04 18:51 UTC, merged

2021-06-04 18:52 UTC, aik099 commented
Merging, thank you @andrewnicols for a fast response.