fix: update phpunit config syntax for phpunit 9
minkphp/Mink pull request #837
Opened 2022-10-29 17:55 UTC by svemir

There are some deprecated elements in phpunit.xml.dist, resulting in this warning on a clean master checkout:
```
> ./vendor/bin/phpunit                                                                                                                        Mink master
PHPUnit 9.5.26 by Sebastian Bergmann and contributors.

Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

Testing
...............................................................  63 / 511 ( 12%)
............................................................... 126 / 511 ( 24%)
............................................................... 189 / 511 ( 36%)
............................................................... 252 / 511 ( 49%)
............................................................... 315 / 511 ( 61%)
............................................................... 378 / 511 ( 73%)
............................................................... 441 / 511 ( 86%)
............................................................... 504 / 511 ( 98%)
.......                                                         511 / 511 (100%)

Time: 00:02.658, Memory: 14.00 MB

OK (511 tests, 910 assertions)

Legacy deprecation notices (128)
```

After applying the suggestion and rearranging the elements to decrease the diff size, it works as expected:
```
> ./vendor/bin/phpunit                                                                                                                Mink phpunit-config
PHPUnit 9.5.26 by Sebastian Bergmann and contributors.

Testing
...............................................................  63 / 511 ( 12%)
............................................................... 126 / 511 ( 24%)
............................................................... 189 / 511 ( 36%)
............................................................... 252 / 511 ( 49%)
............................................................... 315 / 511 ( 61%)
............................................................... 378 / 511 ( 73%)
............................................................... 441 / 511 ( 86%)
............................................................... 504 / 511 ( 98%)
.......                                                         511 / 511 (100%)

Time: 00:02.641, Memory: 14.00 MB

OK (511 tests, 910 assertions)

Legacy deprecation notices (128)
```

2022-10-29 18:02 UTC, svemir commented
Not really sure what's up with the coverage change. On my box the coverage is identical in master and in my branch.

2022-11-01 19:04 UTC, aik099 requested changes

2022-11-01 19:04 UTC, aik099 commented on phpunit.xml.dist
> +    </coverage>
Is this a backward-compatible change? I need the same `phpunit.xml.dist` file to work on every supported PHPUnit version.

2022-11-01 19:16 UTC, svemir commented
In that case this should be closed until php 7.3/phpunit 9 are the minimum requirements.

2022-11-01 19:16 UTC, closed without merging

2022-11-01 19:23 UTC, svemir commented
BTW, once support for phpunit 10 is added, support for phpunit 8 will probably have to be dropped because phpunit 10 drops support for the old coverage configuration.

2022-11-02 08:23 UTC, aik099 commented
IMO it's better to have a warning during the test runs + all possible PHPUnit version configuration options rather than support only latest PHPUnit version.